test:
  image: clojure:lein-2.8.3
  script:
  - lein deps
  - lein test
  - lein run -- hello_world.crisp

pages:
  image: node:9.11.1
  cache:
    paths:
    - doc/node_modules/

  script:
  - cd doc
  - yarn
  - yarn build
  - mv .vuepress/dist ../public-tmp
  - cd ..
  - mv public-tmp public

  artifacts:
    paths:
    - public

  only:
  - master
